events {}

http {

    # 1. HTTP server - only for redirect
    server {
        listen 80;
        server_name _;

        return 301 https://$host$request_uri;
    }

    # 2. HTTPS server - actual content
    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;

        ssl_protocols TLSv1.2 TLSv1.3;

        # for production max-age=31536000 (1 year)
        add_header Strict-Transport-Security "max-age=300; includeSubDomains" always;

        location / {
            root /var/www/html;
            index index.html;
        }
    }
}
